const PRINTING_MACHINES = [
  {
    id: "1PG06",
    name: "1PG-06 Caida (In Progress)",
    brand: "Caida",
    isMES: true,
    processType: "Printing",
    axMachineId: "1PG-06",
    tableName: "[KEP_LOG].[dbo].[View_1PG06_CAIDA]",
    timestampColumn: "[SERVER TIMESTAMP]",
    columns: [
      "[SERVER TIMESTAMP]",
      "[CURRENT SPEED] AS [LINE_SPEED]",
      "[TOTAL length] AS [TOTAL_length]",
      "[RewingA length] AS [RewingA_length]",
      "[RewingB length] AS [RewingB_length]",
      "[UnwingA length] AS [UnwingA_length]",
      "[UnwingB length] AS [UnwingB_length]",
      "[1U Roll C] AS [1U_Roll_C]",
      "[1U WORK] AS [1U_WORK]",
      "[2U Roll C] AS [2U_Roll_C]",
      "[2U WORK] AS [2U_WORK]",
      "[3U Roll C] AS [3U_Roll_C]",
      "[3U WORK] AS [3U_WORK]",
      "[4U Roll C] AS [4U_Roll_C]",
      "[4U WORK] AS [4U_WORK]",
      "[5U Roll C] AS [5U_Roll_C]",
      "[5U WORK] AS [5U_WORK]",
      "[6U Roll C] AS [6U_Roll_C]",
      "[6U WORK] AS [6U_WORK]",
      "'' AS [7U_Roll_C]",
      "[7U WORK] AS [7U_WORK]",
      "[8U Roll C] AS [8U_Roll_C]",
      "[8U WORK] AS [8U_WORK]",
      "[9U Roll C] AS [9U_Roll_C]",
      "[9U WORK] AS [9U_WORK]",
      "[10U Roll C] AS [10U_Roll_C]",
      "[10U WORK] AS [10U_WORK]",
      "[11U Roll C] AS [11U_Roll_C]",
      "[11U WORK] AS [11U_WORK]",
      "[12U Roll C] AS [12U_Roll_C]",
      "[12U WORK] AS [12U_WORK]",
      "[13U Roll C] AS [13U_Roll_C]",
      "[13U WORK] AS [13U_WORK]",
    ],
  },
  {
    id: "1PG07",
    name: "1PG-07 Caida (In Progress)",
    brand: "Caida",
    isMES: true,
    processType: "Printing",
    axMachineId: "1PG-07",
    tableName: "[KEP_LOG].[dbo].[View_1PG07_CAIDA]",
    timestampColumn: "[SERVER TIMESTAMP]",
    columns: [
      "[SERVER TIMESTAMP]",
      "[CURRENT SPEED] AS [LINE_SPEED]",
      "[TOTAL length] AS [TOTAL_length]",
      "[RewingA length] AS [RewingA_length]",
      "[RewingB length] AS [RewingB_length]",
      "[UnwingA length] AS [UnwingA_length]",
      "[UnwingB length] AS [UnwingB_length]",
      "[1U Roll C] AS [1U_Roll_C]",
      "[1U WORK] AS [1U_WORK]",
      "[2U Roll C] AS [2U_Roll_C]",
      "[2U WORK] AS [2U_WORK]",
      "[3U Roll C] AS [3U_Roll_C]",
      "[3U WORK] AS [3U_WORK]",
      "[4U Roll C] AS [4U_Roll_C]",
      "[4U WORK] AS [4U_WORK]",
      "[5U Roll C] AS [5U_Roll_C]",
      "[5U WORK] AS [5U_WORK]",
      "[6U Roll C] AS [6U_Roll_C]",
      "[6U WORK] AS [6U_WORK]",
      "[7U Roll C] AS [7U_Roll_C]",
      "[7U WORK] AS [7U_WORK]",
      "[8U Roll C] AS [8U_Roll_C]",
      "[8U WORK] AS [8U_WORK]",
      "[9U Roll C] AS [9U_Roll_C]",
      "[9U WORK] AS [9U_WORK]",
      "[10U Roll C] AS [10U_Roll_C]",
      "[10U WORK] AS [10U_WORK]",
      "[11U Roll C] AS [11U_Roll_C]",
      "[11U WORK] AS [11U_WORK]",
      "[12U Roll C] AS [12U_Roll_C]",
      "[12U WORK] AS [12U_WORK]",
      "[13U Roll C] AS [13U_Roll_C]",
      "[13U WORK] AS [13U_WORK]",
    ],
  },
  {
    id: "2PG05",
    name: "2PG-05 Beiren",
    brand: "Beiren",
    isMES: false,
    processType: "Printing",
    axMachineId: "2PG-05",
    tableName: null,
    columns: [],
  },
  {
    id: "PT03",
    name: "PT-03 Xinda",
    brand: "Xinda",
    isMES: false,
    processType: "Printing",
    axMachineId: "PT-03",
    tableName: null,
    columns: [],
  },
  {
    id: "PT04",
    name: "PT-04 Beiren (In Progress)",
    brand: "Beiren",
    isMES: true,
    processType: "Printing",
    axMachineId: "PT-04",
    tableName: "[KEP_LOG].[dbo].[View_PT04_Beiren]",
    timestampColumn: "[SERVER TIMESTAMP]",
    columns: [
      "[SERVER TIMESTAMP]",
      "[Main Speed] as [LINE_SPEED]",
      "[RewinderA length] as [RewingA_length]",
      "[RewinderB length] as [RewingB_length]",
      "[Unwind Cutting Length] as [TOTAL_length]",
    ],
  },
  {
    id: "PT08",
    name: "PT-08 Altima (In Progress)",
    brand: "Altima",
    isMES: true,
    processType: "Printing",
    axMachineId: "PT-08",
    tableName: null,
    columns: [],
  },
];

module.exports = {
  PRINTING_MACHINES,
};
