const PRINTING_PARAMETERS = [
  { key: "LINE_SPEED", param_id: 1, name: "Printing Speed", category: "Speed", set_point: "", unit: "m/min", type: "numeric" },
  { key: "TOTAL_length", param_id: 2, name: "Total length", category: "Length", set_point: "", unit: "M", type: "numeric" },
  { key: "RewingA_length", param_id: 3, name: "Rewing A length", category: "Length", set_point: "", unit: "M", type: "numeric" },
  { key: "RewingB_length", param_id: 4, name: "Rewing B length", category: "Length", set_point: "", unit: "M", type: "numeric" },
  { key: "UnwingA_length", param_id: 5, name: "Unwing A length", category: "Length", set_point: "", unit: "M", type: "numeric" },
  { key: "UnwingB_length", param_id: 6, name: "Unwing B length", category: "Length", set_point: "", unit: "M", type: "numeric" },
  { key: "1U_Roll_C", param_id: 7, name: "1U Roll", category: "Roll & Work", set_point: "", unit: "", type: "numeric" },
  { key: "1U_WORK", param_id: 8, name: "1U Work", category: "Roll & Work", set_point: "", unit: "", type: "numeric" },
  { key: "2U_Roll_C", param_id: 9, name: "2U Roll", category: "Roll & Work", set_point: "", unit: "", type: "numeric" },
  { key: "2U_WORK", param_id: 10, name: "2U Work", category: "Roll & Work", set_point: "", unit: "", type: "numeric" },
  { key: "3U_Roll_C", param_id: 11, name: "3U Roll", category: "Roll & Work", set_point: "", unit: "", type: "numeric" },
  { key: "3U_WORK", param_id: 12, name: "3U Work", category: "Roll & Work", set_point: "", unit: "", type: "numeric" },
  { key: "4U_Roll_C", param_id: 13, name: "4U Roll", category: "Roll & Work", set_point: "", unit: "", type: "numeric" },
  { key: "4U_WORK", param_id: 14, name: "4U Work", category: "Roll & Work", set_point: "", unit: "", type: "numeric" },
  { key: "5U_Roll_C", param_id: 15, name: "5U Roll", category: "Roll & Work", set_point: "", unit: "", type: "numeric" },
  { key: "5U_WORK", param_id: 16, name: "5U Work", category: "Roll & Work", set_point: "", unit: "", type: "numeric" },
  { key: "6U_Roll_C", param_id: 17, name: "6U Roll", category: "Roll & Work", set_point: "", unit: "", type: "numeric" },
  { key: "6U_WORK", param_id: 18, name: "6U Work", category: "Roll & Work", set_point: "", unit: "", type: "numeric" },
  { key: "7U_Roll_C", param_id: 19, name: "7U Roll", category: "Roll & Work", set_point: "", unit: "", type: "numeric" },
  { key: "7U_WORK", param_id: 20, name: "7U Work", category: "Roll & Work", set_point: "", unit: "", type: "numeric" },
  { key: "8U_Roll_C", param_id: 21, name: "8U Roll", category: "Roll & Work", set_point: "", unit: "", type: "numeric" },
  { key: "8U_WORK", param_id: 22, name: "8U Work", category: "Roll & Work", set_point: "", unit: "", type: "numeric" },
  { key: "9U_Roll_C", param_id: 23, name: "9U Roll", category: "Roll & Work", set_point: "", unit: "", type: "numeric" },
  { key: "9U_WORK", param_id: 24, name: "9U Work", category: "Roll & Work", set_point: "", unit: "", type: "numeric" },
  { key: "10U_Roll_C", param_id: 25, name: "10U Roll", category: "Roll & Work", set_point: "", unit: "", type: "numeric" },
  { key: "10U_WORK", param_id: 26, name: "10U Work", category: "Roll & Work", set_point: "", unit: "", type: "numeric" },
  { key: "11U_Roll_C", param_id: 27, name: "11U Roll", category: "Roll & Work", set_point: "", unit: "", type: "numeric" },
  { key: "11U_WORK", param_id: 28, name: "11U Work", category: "Roll & Work", set_point: "", unit: "", type: "numeric" },
  { key: "12U_Roll_C", param_id: 29, name: "12U Roll", category: "Roll & Work", set_point: "", unit: "", type: "numeric" },
  { key: "12U_WORK", param_id: 30, name: "12U Work", category: "Roll & Work", set_point: "", unit: "", type: "numeric" },
  { key: "13U_Roll_C", param_id: 31, name: "13U Roll", category: "Roll & Work", set_point: "", unit: "", type: "numeric" },
  { key: "13U_WORK", param_id: 32, name: "13U Work", category: "Roll & Work", set_point: "", unit: "", type: "numeric" },
];

module.exports = {
  PRINTING_PARAMETERS,
};
