// Base Mapping from [AX50_SF_PRD_SP1].[dbo].[SF_PRODSPECMACHINE] to STANDARD_PARAMETERS keys for Laminate
const BASE_AX_PS_MAP = {
  LINE_SPEED: "[SPEED1] AS LINE_SPEED",
  SPLICE_SPEED: "[SPEED2] AS SPLICE_SPEED",
  TEMP_ZONE_1: "[TEMPZONE11] AS TEMP_ZONE_1",
  TEMP_ZONE_2:
    "CASE WHEN [TEMPZONE21] IS NULL OR LTRIM(RTRIM([TEMPZONE21])) = '' OR LTRIM(RTRIM([TEMPZONE21])) = '0' THEN [TEMPZONE22] ELSE [TEMPZONE21] END AS TEMP_ZONE_2",
  TEMP_ZONE_3: "[TEMPZONE31] AS TEMP_ZONE_3",
  TEMP_ZONE_4: "[TEMPZONE41] AS TEMP_ZONE_4",
  TEMP_TANK_A: "[TEMPTANKA1] AS TEMP_TANK_A",
  TEMP_A_B: "[TEMPTANKA2] AS TEMP_A_B",
  TEMP_HOSE_AB: "[ADHESIVEHOSEAB1] AS TEMP_HOSE_AB",
  TEMP_COATING_FM_BR_WR: "[COATINGUNITHEAT1] AS TEMP_COATING_FM_BR_WR",
  TEMP_LAMINATOR_HOT_ROLL: "[LAMINATEHEAT1] AS TEMP_LAMINATOR_HOT_ROLL",
  TENSION_UNWIND_1: "[UNWINDERTENSION11] AS TENSION_UNWIND_1",
  TENSION_UNWIND_2:
    "CASE WHEN [UNWINDERTENSION12] IS NULL OR LTRIM(RTRIM([UNWINDERTENSION12])) = '' OR LTRIM(RTRIM([UNWINDERTENSION12])) = '0' THEN [UNWINDERTENSION21] ELSE [UNWINDERTENSION12] END AS TENSION_UNWIND_2",
  TENSION_REWIND: "[REWINDER1] AS TENSION_REWIND",
  TENSION_TAPER_REWIND: "[TAPERTENSION1] AS TENSION_TAPER_REWIND",
  PRESSURE_COATING_GR_OP: `CASE
    WHEN CHARINDEX('-',
      CASE WHEN [COATINGROLLER1] IS NULL OR LTRIM(RTRIM([COATINGROLLER1])) = '' OR LTRIM(RTRIM([COATINGROLLER1])) = '0'
            THEN [COATINGROLLER2] ELSE [COATINGROLLER1] END
    ) > 0
    THEN LTRIM(RTRIM(SUBSTRING(
      CASE WHEN [COATINGROLLER1] IS NULL OR LTRIM(RTRIM([COATINGROLLER1])) = '' OR LTRIM(RTRIM([COATINGROLLER1])) = '0'
            THEN [COATINGROLLER2] ELSE [COATINGROLLER1] END,
      CHARINDEX('-',
        CASE WHEN [COATINGROLLER1] IS NULL OR LTRIM(RTRIM([COATINGROLLER1])) = '' OR LTRIM(RTRIM([COATINGROLLER1])) = '0'
              THEN [COATINGROLLER2] ELSE [COATINGROLLER1] END
      ) + 1,
      LEN(CASE WHEN [COATINGROLLER1] IS NULL OR LTRIM(RTRIM([COATINGROLLER1])) = '' OR LTRIM(RTRIM([COATINGROLLER1])) = '0'
                THEN [COATINGROLLER2] ELSE [COATINGROLLER1] END)
    )))
    ELSE CASE WHEN [COATINGROLLER1] IS NULL OR LTRIM(RTRIM([COATINGROLLER1])) = '' OR LTRIM(RTRIM([COATINGROLLER1])) = '0'
              THEN [COATINGROLLER2] ELSE [COATINGROLLER1] END
  END AS PRESSURE_COATING_GR_OP`,
  PRESSURE_COATING_GR_MO: `CASE
    WHEN CHARINDEX('-',
      CASE WHEN [COATINGROLLER1] IS NULL OR LTRIM(RTRIM([COATINGROLLER1])) = '' OR LTRIM(RTRIM([COATINGROLLER1])) = '0'
            THEN [COATINGROLLER2] ELSE [COATINGROLLER1] END
    ) > 0
    THEN LTRIM(RTRIM(LEFT(
      CASE WHEN [COATINGROLLER1] IS NULL OR LTRIM(RTRIM([COATINGROLLER1])) = '' OR LTRIM(RTRIM([COATINGROLLER1])) = '0'
            THEN [COATINGROLLER2] ELSE [COATINGROLLER1] END,
      CHARINDEX('-',
        CASE WHEN [COATINGROLLER1] IS NULL OR LTRIM(RTRIM([COATINGROLLER1])) = '' OR LTRIM(RTRIM([COATINGROLLER1])) = '0'
              THEN [COATINGROLLER2] ELSE [COATINGROLLER1] END
      ) - 1
    )))
    ELSE CASE WHEN [COATINGROLLER1] IS NULL OR LTRIM(RTRIM([COATINGROLLER1])) = '' OR LTRIM(RTRIM([COATINGROLLER1])) = '0'
              THEN [COATINGROLLER2] ELSE [COATINGROLLER1] END
  END AS PRESSURE_COATING_GR_MO`,
  PRESSURE_COATING_FR_MO: `CASE
    WHEN CHARINDEX('-', [NIPROLLPRESSURE_UPPER]) > 0 AND CHARINDEX('/', [NIPROLLPRESSURE_UPPER]) > 0
    THEN
      LEFT(
        LEFT([NIPROLLPRESSURE_UPPER], CHARINDEX('-', [NIPROLLPRESSURE_UPPER]) - 1),
        CHARINDEX('/', LEFT([NIPROLLPRESSURE_UPPER], CHARINDEX('-', [NIPROLLPRESSURE_UPPER]) - 1)) - 1
      )
      + '-' +
      LEFT(
        SUBSTRING([NIPROLLPRESSURE_UPPER], CHARINDEX('-', [NIPROLLPRESSURE_UPPER]) + 1, LEN([NIPROLLPRESSURE_UPPER])),
        CHARINDEX('/', SUBSTRING([NIPROLLPRESSURE_UPPER], CHARINDEX('-', [NIPROLLPRESSURE_UPPER]) + 1, LEN([NIPROLLPRESSURE_UPPER]))) - 1
      )
    ELSE [NIPROLLPRESSURE_UPPER]
  END AS PRESSURE_COATING_FR_MO`,
  PRESSURE_COATING_FR_OP: `CASE
    WHEN CHARINDEX('-', [NIPROLLPRESSURE_UPPER]) > 0 AND CHARINDEX('/', [NIPROLLPRESSURE_UPPER]) > 0
    THEN
      SUBSTRING(
        LEFT([NIPROLLPRESSURE_UPPER], CHARINDEX('-', [NIPROLLPRESSURE_UPPER]) - 1),
        CHARINDEX('/', LEFT([NIPROLLPRESSURE_UPPER], CHARINDEX('-', [NIPROLLPRESSURE_UPPER]) - 1)) + 1,
        LEN(LEFT([NIPROLLPRESSURE_UPPER], CHARINDEX('-', [NIPROLLPRESSURE_UPPER]) - 1))
      )
      + '-' +
      SUBSTRING(
        SUBSTRING([NIPROLLPRESSURE_UPPER], CHARINDEX('-', [NIPROLLPRESSURE_UPPER]) + 1, LEN([NIPROLLPRESSURE_UPPER])),
        CHARINDEX('/', SUBSTRING([NIPROLLPRESSURE_UPPER], CHARINDEX('-', [NIPROLLPRESSURE_UPPER]) + 1, LEN([NIPROLLPRESSURE_UPPER]))) + 1,
        LEN(SUBSTRING([NIPROLLPRESSURE_UPPER], CHARINDEX('-', [NIPROLLPRESSURE_UPPER]) + 1, LEN([NIPROLLPRESSURE_UPPER])))
      )
    ELSE [NIPROLLPRESSURE_UPPER]
  END AS PRESSURE_COATING_FR_OP`,
  TENSION_INLET_COATING:
    "CASE WHEN [FEEDTENSION1] IS NULL OR LTRIM(RTRIM([FEEDTENSION1])) = '' OR LTRIM(RTRIM([FEEDTENSION1])) = '0' THEN [DANCERROLLTENSION1] ELSE [FEEDTENSION1] END AS TENSION_INLET_COATING",
  TENSION_OUTLET_COATING:
    "CASE WHEN [FEEDTENSION2] IS NULL OR LTRIM(RTRIM([FEEDTENSION2])) = '' OR LTRIM(RTRIM([FEEDTENSION2])) = '0' THEN [DANCERROLLTENSION1] ELSE [FEEDTENSION2] END AS TENSION_OUTLET_COATING",
  TENSION_UNWIND2_INFEED: "[INFEEDINGTENSION] AS TENSION_UNWIND2_INFEED",
  PRESSURE_NIP_OPERATOR: `CASE
    WHEN CHARINDEX('-', [DANCERROLLTENSION1]) > 0
    THEN LTRIM(RTRIM(SUBSTRING(
      [DANCERROLLTENSION1],
      CHARINDEX('-', [DANCERROLLTENSION1]) + 1,
      LEN([DANCERROLLTENSION1])
    )))
    ELSE [DANCERROLLTENSION1]
  END AS PRESSURE_NIP_OPERATOR`,
  PRESSURE_NIP_MOTOR: `CASE
    WHEN CHARINDEX('-', [DANCERROLLTENSION1]) > 0
    THEN LTRIM(RTRIM(LEFT(
      [DANCERROLLTENSION1],
      CHARINDEX('-', [DANCERROLLTENSION1]) - 1
    )))
    ELSE [DANCERROLLTENSION1]
  END AS PRESSURE_NIP_MOTOR`,
  SMOOTHING_ROLL: "[SMOOTINGROLL1] AS SMOOTHING_ROLL",
  CORONA_INSIDE: "[CORONATREAT11] AS CORONA_INSIDE",
  CORONA_OUTSIDE: "[CORONATREAT21] AS CORONA_OUTSIDE",
  CORONA_POWER_UW1: "[CORONA] AS CORONA_POWER_UW1",
  CORONA_POWER_UW2: "[CORONA2] AS CORONA_POWER_UW2",
};

/**
 * Returns the final array of SQL select expressions for AX Set Point query.
 * If machineConfig has axPsColumns (full list), it uses that.
 * If machineConfig has axPsOverrides, it overrides specific keys in BASE_AX_PS_MAP.
 * Otherwise, it uses all base mappings.
 */
function getAxPsColumns(machineConfig) {
  if (machineConfig && machineConfig.axPsColumns && Array.isArray(machineConfig.axPsColumns)) {
    return machineConfig.axPsColumns;
  }
  const overrides = (machineConfig && machineConfig.axPsOverrides) || {};
  const merged = { ...BASE_AX_PS_MAP, ...overrides };
  return Object.values(merged);
}

// Flat array for default Laminate AX Set Point columns
const AX_PS_COLUMNS = Object.values(BASE_AX_PS_MAP);

module.exports = {
  BASE_AX_PS_MAP,
  AX_PS_COLUMNS,
  getAxPsColumns,
};
