// Mapping columns from [AX50_SF_PRD_SP1].[dbo].[SF_PRODSPECMACHINE] to STANDARD_PARAMETERS keys for Laminate
const AX_PS_COLUMNS = [
  "[SPEED1] AS LINE_SPEED",
  "[SPEED2] AS SPLICE_SPEED",
  "[TEMPZONE11] AS TEMP_ZONE_1",
  "CASE WHEN [TEMPZONE21] IS NULL OR LTRIM(RTRIM([TEMPZONE21])) = '' OR LTRIM(RTRIM([TEMPZONE21])) = '0' THEN [TEMPZONE22] ELSE [TEMPZONE21] END AS TEMP_ZONE_2",
  "[TEMPZONE31] AS TEMP_ZONE_3",
  "[TEMPZONE41] AS TEMP_ZONE_4",
  "[TEMPTANKA1] AS TEMP_TANK_A",
  "[TEMPTANKA2] AS TEMP_A_B",
  "[ADHESIVEHOSEAB1] AS TEMP_HOSE_AB",
  "[COATINGUNITHEAT1] AS TEMP_COATING_FM_BR_WR",
  "[LAMINATEHEAT1] AS TEMP_LAMINATOR_HOT_ROLL",
  "[UNWINDERTENSION11] AS TENSION_UNWIND_1",
  "CASE WHEN [UNWINDERTENSION12] IS NULL OR LTRIM(RTRIM([UNWINDERTENSION12])) = '' OR LTRIM(RTRIM([UNWINDERTENSION12])) = '0' THEN [UNWINDERTENSION21] ELSE [UNWINDERTENSION12] END AS TENSION_UNWIND_2",
  "[REWINDER1] AS TENSION_REWIND",
  "[TAPERTENSION1] AS TENSION_TAPER_REWIND",
  `CASE
    WHEN CHARINDEX('-',
      CASE WHEN [COATINGROLLER1] IS NULL OR LTRIM(RTRIM([COATINGROLLER1])) = '' OR LTRIM(RTRIM([COATINGROLLER1])) = '0'
            THEN [COATINGROLLER2] ELSE [COATINGROLLER1] END
    ) > 0
    THEN LTRIM(RTRIM(SUBSTRING(
      CASE WHEN [COATINGROLLER1] IS NULL OR LTRIM(RTRIM([COATINGROLLER1])) = '' OR LTRIM(RTRIM([COATINGROLLER1])) = '0'
            THEN [COATINGROLLER2] ELSE [COATINGROLLER1] END,
      CHARINDEX('-',
        CASE WHEN [COATINGROLLER1] IS NULL OR LTRIM(RTRIM([COATINGROLLER1])) = '' OR LTRIM(RTRIM([COATINGROLLER1])) = '0'
              THEN [COATINGROLLER2] ELSE [COATINGROLLER1] END
      ) + 1,
      LEN(CASE WHEN [COATINGROLLER1] IS NULL OR LTRIM(RTRIM([COATINGROLLER1])) = '' OR LTRIM(RTRIM([COATINGROLLER1])) = '0'
                THEN [COATINGROLLER2] ELSE [COATINGROLLER1] END)
    )))
    ELSE CASE WHEN [COATINGROLLER1] IS NULL OR LTRIM(RTRIM([COATINGROLLER1])) = '' OR LTRIM(RTRIM([COATINGROLLER1])) = '0'
              THEN [COATINGROLLER2] ELSE [COATINGROLLER1] END
  END AS PRESSURE_COATING_GR_OP`,
  `CASE
    WHEN CHARINDEX('-',
      CASE WHEN [COATINGROLLER1] IS NULL OR LTRIM(RTRIM([COATINGROLLER1])) = '' OR LTRIM(RTRIM([COATINGROLLER1])) = '0'
            THEN [COATINGROLLER2] ELSE [COATINGROLLER1] END
    ) > 0
    THEN LTRIM(RTRIM(LEFT(
      CASE WHEN [COATINGROLLER1] IS NULL OR LTRIM(RTRIM([COATINGROLLER1])) = '' OR LTRIM(RTRIM([COATINGROLLER1])) = '0'
            THEN [COATINGROLLER2] ELSE [COATINGROLLER1] END,
      CHARINDEX('-',
        CASE WHEN [COATINGROLLER1] IS NULL OR LTRIM(RTRIM([COATINGROLLER1])) = '' OR LTRIM(RTRIM([COATINGROLLER1])) = '0'
              THEN [COATINGROLLER2] ELSE [COATINGROLLER1] END
      ) - 1
    )))
    ELSE CASE WHEN [COATINGROLLER1] IS NULL OR LTRIM(RTRIM([COATINGROLLER1])) = '' OR LTRIM(RTRIM([COATINGROLLER1])) = '0'
              THEN [COATINGROLLER2] ELSE [COATINGROLLER1] END
  END AS PRESSURE_COATING_GR_MO`,
  "[FEEDROLLERPRESSURE1] AS PRESSURE_COATING_FR_OP",
  "[FEEDROLLERPRESSURE2] AS PRESSURE_COATING_FR_MO",
  "[FEEDTENSION1] AS TENSION_INLET_COATING",
  "[FEEDTENSION2] AS TENSION_OUTLET_COATING",
  "[INFEEDINGTENSION] AS TENSION_UNWIND2_INFEED",
  `CASE
    WHEN CHARINDEX('-', [DANCERROLLTENSION1]) > 0
    THEN LTRIM(RTRIM(SUBSTRING(
      [DANCERROLLTENSION1],
      CHARINDEX('-', [DANCERROLLTENSION1]) + 1,
      LEN([DANCERROLLTENSION1])
    )))
    ELSE [DANCERROLLTENSION1]
  END AS PRESSURE_NIP_OPERATOR`,
  `CASE
    WHEN CHARINDEX('-', [DANCERROLLTENSION1]) > 0
    THEN LTRIM(RTRIM(LEFT(
      [DANCERROLLTENSION1],
      CHARINDEX('-', [DANCERROLLTENSION1]) - 1
    )))
    ELSE [DANCERROLLTENSION1]
  END AS PRESSURE_NIP_MOTOR`,
  "[SMOOTINGROLL1] AS SMOOTHING_ROLL",
  "[CORONATREAT11] AS CORONA_INSIDE",
  "[CORONATREAT21] AS CORONA_OUTSIDE",
  "[CORONA] AS CORONA_POWER_UW1",
  "[CORONA2] AS CORONA_POWER_UW2",
];

module.exports = {
  AX_PS_COLUMNS,
};

// `CASE
//   WHEN [TEMPTANKA1] IS NOT NULL AND [TEMPTANKA1] <> '' AND [TEMPTANKA2] IS NOT NULL AND [TEMPTANKA2] <> '' THEN [TEMPTANKA1] + ', ' + [TEMPTANKA2]
//   WHEN [TEMPTANKA1] IS NOT NULL AND [TEMPTANKA1] <> '' THEN [TEMPTANKA1]
//   WHEN [TEMPTANKA2] IS NOT NULL AND [TEMPTANKA2] <> '' THEN [TEMPTANKA2]
//   ELSE ''
//   END AS `, //[TEMPTANKA1] + ', ' + [TEMPTANKA2] AS TEMP_A_B
