// Mapping columns from [AX50_SF_PRD_SP1].[dbo].[SF_PRODSPECMACHINE] to STANDARD_PARAMETERS keys for Laminate
const AX_PS_COLUMNS = [
  "[SPEED1] AS LINE_SPEED",
  "[SPEED2] AS SPLICE_SPEED",
  "[TEMPZONE11] AS TEMP_ZONE_1",
  "CASE WHEN [TEMPZONE21] IS NULL OR LTRIM(RTRIM([TEMPZONE21])) = '' OR LTRIM(RTRIM([TEMPZONE21])) = '0' THEN [TEMPZONE22] ELSE [TEMPZONE21] END AS TEMP_ZONE_2",
  "[TEMPZONE31] AS TEMP_ZONE_3",
  "[TEMPZONE41] AS TEMP_ZONE_4",
  "[TEMPTANKA1] AS TEMP_TANK_A",
  "[TEMPTANKA2] AS TEMP_A_B",
  "[ADHESIVEHOSEAB1] AS TEMP_HOSE_AB",
  "[COATINGUNITHEAT1] AS TEMP_COATING_FM_BR_WR",
  "[LAMINATEHEAT1] AS TEMP_LAMINATOR_HOT_ROLL",
  "[UNWINDERTENSION11] AS TENSION_UNWIND_1",
  "CASE WHEN [UNWINDERTENSION12] IS NULL OR LTRIM(RTRIM([UNWINDERTENSION12])) = '' OR LTRIM(RTRIM([UNWINDERTENSION12])) = '0' THEN [UNWINDERTENSION21] ELSE [UNWINDERTENSION12] END AS TENSION_UNWIND_2",
  "[REWINDER1] AS TENSION_REWIND",
  "[TAPERTENSION1] AS TENSION_TAPER_REWIND",
  `CASE
    WHEN CHARINDEX('-',
      CASE WHEN [COATINGROLLER1] IS NULL OR LTRIM(RTRIM([COATINGROLLER1])) = '' OR LTRIM(RTRIM([COATINGROLLER1])) = '0'
            THEN [COATINGROLLER2] ELSE [COATINGROLLER1] END
    ) > 0
    THEN LTRIM(RTRIM(SUBSTRING(
      CASE WHEN [COATINGROLLER1] IS NULL OR LTRIM(RTRIM([COATINGROLLER1])) = '' OR LTRIM(RTRIM([COATINGROLLER1])) = '0'
            THEN [COATINGROLLER2] ELSE [COATINGROLLER1] END,
      CHARINDEX('-',
        CASE WHEN [COATINGROLLER1] IS NULL OR LTRIM(RTRIM([COATINGROLLER1])) = '' OR LTRIM(RTRIM([COATINGROLLER1])) = '0'
              THEN [COATINGROLLER2] ELSE [COATINGROLLER1] END
      ) + 1,
      LEN(CASE WHEN [COATINGROLLER1] IS NULL OR LTRIM(RTRIM([COATINGROLLER1])) = '' OR LTRIM(RTRIM([COATINGROLLER1])) = '0'
                THEN [COATINGROLLER2] ELSE [COATINGROLLER1] END)
    )))
    ELSE CASE WHEN [COATINGROLLER1] IS NULL OR LTRIM(RTRIM([COATINGROLLER1])) = '' OR LTRIM(RTRIM([COATINGROLLER1])) = '0'
              THEN [COATINGROLLER2] ELSE [COATINGROLLER1] END
  END AS PRESSURE_COATING_GR_OP`,
  `CASE
    WHEN CHARINDEX('-',
      CASE WHEN [COATINGROLLER1] IS NULL OR LTRIM(RTRIM([COATINGROLLER1])) = '' OR LTRIM(RTRIM([COATINGROLLER1])) = '0'
            THEN [COATINGROLLER2] ELSE [COATINGROLLER1] END
    ) > 0
    THEN LTRIM(RTRIM(LEFT(
      CASE WHEN [COATINGROLLER1] IS NULL OR LTRIM(RTRIM([COATINGROLLER1])) = '' OR LTRIM(RTRIM([COATINGROLLER1])) = '0'
            THEN [COATINGROLLER2] ELSE [COATINGROLLER1] END,
      CHARINDEX('-',
        CASE WHEN [COATINGROLLER1] IS NULL OR LTRIM(RTRIM([COATINGROLLER1])) = '' OR LTRIM(RTRIM([COATINGROLLER1])) = '0'
              THEN [COATINGROLLER2] ELSE [COATINGROLLER1] END
      ) - 1
    )))
    ELSE CASE WHEN [COATINGROLLER1] IS NULL OR LTRIM(RTRIM([COATINGROLLER1])) = '' OR LTRIM(RTRIM([COATINGROLLER1])) = '0'
              THEN [COATINGROLLER2] ELSE [COATINGROLLER1] END
  END AS PRESSURE_COATING_GR_MO`,
  `CASE
    WHEN CHARINDEX('-', [NIPROLLPRESSURE_UPPER]) > 0 AND CHARINDEX('/', [NIPROLLPRESSURE_UPPER]) > 0
    THEN
      LEFT(
        LEFT([NIPROLLPRESSURE_UPPER], CHARINDEX('-', [NIPROLLPRESSURE_UPPER]) - 1),
        CHARINDEX('/', LEFT([NIPROLLPRESSURE_UPPER], CHARINDEX('-', [NIPROLLPRESSURE_UPPER]) - 1)) - 1
      )
      + '-' +
      LEFT(
        SUBSTRING([NIPROLLPRESSURE_UPPER], CHARINDEX('-', [NIPROLLPRESSURE_UPPER]) + 1, LEN([NIPROLLPRESSURE_UPPER])),
        CHARINDEX('/', SUBSTRING([NIPROLLPRESSURE_UPPER], CHARINDEX('-', [NIPROLLPRESSURE_UPPER]) + 1, LEN([NIPROLLPRESSURE_UPPER]))) - 1
      )
    ELSE [NIPROLLPRESSURE_UPPER]
  END AS PRESSURE_COATING_FR_MO`,
  `CASE
    WHEN CHARINDEX('-', [NIPROLLPRESSURE_UPPER]) > 0 AND CHARINDEX('/', [NIPROLLPRESSURE_UPPER]) > 0
    THEN
      SUBSTRING(
        LEFT([NIPROLLPRESSURE_UPPER], CHARINDEX('-', [NIPROLLPRESSURE_UPPER]) - 1),
        CHARINDEX('/', LEFT([NIPROLLPRESSURE_UPPER], CHARINDEX('-', [NIPROLLPRESSURE_UPPER]) - 1)) + 1,
        LEN(LEFT([NIPROLLPRESSURE_UPPER], CHARINDEX('-', [NIPROLLPRESSURE_UPPER]) - 1))
      )
      + '-' +
      SUBSTRING(
        SUBSTRING([NIPROLLPRESSURE_UPPER], CHARINDEX('-', [NIPROLLPRESSURE_UPPER]) + 1, LEN([NIPROLLPRESSURE_UPPER])),
        CHARINDEX('/', SUBSTRING([NIPROLLPRESSURE_UPPER], CHARINDEX('-', [NIPROLLPRESSURE_UPPER]) + 1, LEN([NIPROLLPRESSURE_UPPER]))) + 1,
        LEN(SUBSTRING([NIPROLLPRESSURE_UPPER], CHARINDEX('-', [NIPROLLPRESSURE_UPPER]) + 1, LEN([NIPROLLPRESSURE_UPPER])))
      )
    ELSE [NIPROLLPRESSURE_UPPER]
  END AS PRESSURE_COATING_FR_OP`,
  "CASE WHEN [FEEDTENSION1] IS NULL OR LTRIM(RTRIM([FEEDTENSION1])) = '' OR LTRIM(RTRIM([FEEDTENSION1])) = '0' THEN [DANCERROLLTENSION1] ELSE [FEEDTENSION1] END AS TENSION_INLET_COATING",
  "CASE WHEN [FEEDTENSION2] IS NULL OR LTRIM(RTRIM([FEEDTENSION2])) = '' OR LTRIM(RTRIM([FEEDTENSION2])) = '0' THEN [DANCERROLLTENSION1] ELSE [FEEDTENSION2] END AS TENSION_OUTLET_COATING",
  "[INFEEDINGTENSION] AS TENSION_UNWIND2_INFEED",
  `CASE
    WHEN CHARINDEX('-', [DANCERROLLTENSION1]) > 0
    THEN LTRIM(RTRIM(SUBSTRING(
      [DANCERROLLTENSION1],
      CHARINDEX('-', [DANCERROLLTENSION1]) + 1,
      LEN([DANCERROLLTENSION1])
    )))
    ELSE [DANCERROLLTENSION1]
  END AS PRESSURE_NIP_OPERATOR`,
  `CASE
    WHEN CHARINDEX('-', [DANCERROLLTENSION1]) > 0
    THEN LTRIM(RTRIM(LEFT(
      [DANCERROLLTENSION1],
      CHARINDEX('-', [DANCERROLLTENSION1]) - 1
    )))
    ELSE [DANCERROLLTENSION1]
  END AS PRESSURE_NIP_MOTOR`,
  "[SMOOTINGROLL1] AS SMOOTHING_ROLL",
  "[CORONATREAT11] AS CORONA_INSIDE",
  "[CORONATREAT21] AS CORONA_OUTSIDE",
  "[CORONA] AS CORONA_POWER_UW1",
  "[CORONA2] AS CORONA_POWER_UW2",
];

// AX PS Mapping specifically for 2LB-06 (Fuji Kikai)
const AX_PS_COLUMNS_2LB06 = [
  "[SPEED1] AS LINE_SPEED",
  "[SPEED2] AS SPLICE_SPEED",
  "[TEMPZONE11] AS TEMP_ZONE_1",
  "[TEMPZONE21] AS TEMP_ZONE_2",
  "[TEMPZONE31] AS TEMP_ZONE_3",
  "[LAMINATEHEAT1] AS TEMP_LAMINATOR_HOT_ROLL",
  "[UNWINDERTENSION11] AS TENSION_UNWIND_1",
  "CASE WHEN [UNWINDERTENSION12] IS NULL OR LTRIM(RTRIM([UNWINDERTENSION12])) = '' OR LTRIM(RTRIM([UNWINDERTENSION12])) = '0' THEN [UNWINDERTENSION21] ELSE [UNWINDERTENSION12] END AS TENSION_UNWIND_2",
  "[REWINDER1] AS TENSION_REWIND",
  "[TAPERTENSION1] AS TENSION_TAPER_REWIND",
  `CASE
    WHEN [IMPRESSIONROLL2] IS NOT NULL AND CHARINDEX('-', [IMPRESSIONROLL2]) > 0
    THEN LTRIM(RTRIM(SUBSTRING([IMPRESSIONROLL2], CHARINDEX('-', [IMPRESSIONROLL2]) + 1, LEN([IMPRESSIONROLL2]))))
    ELSE LTRIM(RTRIM(ISNULL([IMPRESSIONROLL2], '')))
  END AS PRESSURE_COATING_GR_OP`,
  `CASE
    WHEN [IMPRESSIONROLL2] IS NOT NULL AND CHARINDEX('-', [IMPRESSIONROLL2]) > 0
    THEN LTRIM(RTRIM(SUBSTRING([IMPRESSIONROLL2], 1, CHARINDEX('-', [IMPRESSIONROLL2]) - 1)))
    ELSE LTRIM(RTRIM(ISNULL([IMPRESSIONROLL2], '')))
  END AS PRESSURE_COATING_GR_MO`,
  "[FEEDTENSION1] AS TENSION_INLET_COATING",
  "[FEEDTENSION2] AS TENSION_OUTLET_COATING",
  `CASE
    WHEN [IMPRESSIONROLL1] IS NOT NULL AND CHARINDEX('-', [IMPRESSIONROLL1]) > 0
    THEN LTRIM(RTRIM(SUBSTRING([IMPRESSIONROLL1], CHARINDEX('-', [IMPRESSIONROLL1]) + 1, LEN([IMPRESSIONROLL1]))))
    ELSE LTRIM(RTRIM(ISNULL([IMPRESSIONROLL1], '')))
  END AS PRESSURE_NIP_OPERATOR`,
  `CASE
    WHEN [IMPRESSIONROLL1] IS NOT NULL AND CHARINDEX('-', [IMPRESSIONROLL1]) > 0
    THEN LTRIM(RTRIM(SUBSTRING([IMPRESSIONROLL1], 1, CHARINDEX('-', [IMPRESSIONROLL1]) - 1)))
    ELSE LTRIM(RTRIM(ISNULL([IMPRESSIONROLL1], '')))
  END AS PRESSURE_NIP_MOTOR`,
];

module.exports = {
  AX_PS_COLUMNS,
  AX_PS_COLUMNS_2LB06,
};
