const LAMINATE_MACHINES = [
  {
    id: "1LB09",
    name: "1LB09 Bobst",
    brand: "Bobst",
    isMES: true,
    processType: "Laminate",
    axMachineId: "1LB-09",
    tableName: "[KEP_LOG].[dbo].[View_1LB09_Bobst]",
    timestampColumn: "[SERVER TIMESTAMP]",
    columns: [
      "[SERVER TIMESTAMP] AS SERVER_TIMESTAMP",
      "[Machine : Speed] AS LINE_SPEED",
      "[Tunnel : Zone 1 : Temperature] AS TEMP_ZONE_1",
      "[Tunnel : Zone 2 : Temperature] AS TEMP_ZONE_2",
      "[Coating 1- Metering and blade roller- Water- Temperature] AS TEMP_COATING_FM_BR_WR",
      "[Laminator : Hot Roll : Water Temperature] AS TEMP_LAMINATOR_HOT_ROLL",
      "[Unwinder 1 : Tension] AS TENSION_UNWIND_1",
      "[Unwinder 2 : Tension] AS TENSION_UNWIND_2",
      "[Rewinder : Tension] AS TENSION_REWIND",
      "[Rewinder : Tension Taper] AS TENSION_TAPER_REWIND",
      "[Coating : Rotogravure Trolley : CoatingRoll : Nip : Operator : Pressure] AS PRESSURE_COATING_GR_OP",
      "[Coating : Rotogravure Trolley : CoatingRoll : Nip : Motor : Pressure] AS PRESSURE_COATING_GR_MO",
      "[Coating : SI Transfer Roll : Operator : Pressure] AS PRESSURE_COATING_FR_OP",
      "[Coating : SI Transfer Roll : Motor : Pressure] AS PRESSURE_COATING_FR_MO",
      "[Coating : Inlet : Tension] AS TENSION_INLET_COATING",
      "[Coating : Outlet : Tension] AS TENSION_OUTLET_COATING",
      "[Unwinder 2 : Infeed ( D.g ) - Tension] AS TENSION_UNWIND2_INFEED",
      "[Laminator : Nip Roll : Operator : Pressure] AS PRESSURE_NIP_OPERATOR",
      "[Laminator : Nip Roll : Motor : Pressure] AS PRESSURE_NIP_MOTOR",
      "[Coating : Rotogravure Trolley : Smoothing Roll Speed] AS SMOOTHING_ROLL",
      "[Unwinder 1 : Treatment : Specific Power] AS CORONA_POWER_UW1",
      "[Unwinder 2 : Corona : Specific Power] AS CORONA_POWER_UW2",
    ],
    unitOverrides: {
      TENSION_UNWIND_1: "N",
      TENSION_UNWIND_2: "N",
      TENSION_REWIND: "N",
      PRESSURE_NIP_OPERATOR: "Bar",
      PRESSURE_NIP_MOTOR: "Bar",
      PRESSURE_COATING_GR_OP: "Bar",
      PRESSURE_COATING_GR_MO: "Bar",
      PRESSURE_COATING_FR_OP: "Bar",
      PRESSURE_COATING_FR_MO: "Bar",
    },
  },
  {
    id: "LB10",
    name: "LB-10 Bobst",
    brand: "Bobst",
    isMES: false,
    processType: "Laminate",
    axMachineId: "LB-10",
    tableName: null,
    columns: [],
  },
  {
    id: "1LL07",
    name: "1LL-07 Comexi",
    brand: "Comexi",
    isMES: true,
    processType: "Laminate",
    axMachineId: "1LL-07",
    tableName: "[KEP_LOG].[dbo].[View_1LL07_Comexi]",
    timestampColumn: "[SERVER TIMESTAMP]",
    columns: [],
  },
  {
    id: "2LB06",
    name: "2LB06 Fuji Kikai",
    brand: "FujiKikai",
    isMES: true,
    processType: "Laminate",
    axMachineId: "2LB-06",
    tableName: "[KEP_LOG].[dbo].[View_2LB06_FujiKikai]",
    timestampColumn: "[SERVER TIMESTAMP]",
    columns: [
      "[SERVER TIMESTAMP] AS SERVER_TIMESTAMP",
      "[Speed.Processing Speed] AS LINE_SPEED",
      "[Temp.No.1 Zone] AS TEMP_ZONE_1",
      "[Temp.No.2 Zone] AS TEMP_ZONE_2",
      "[Temp.No.3 Zone] AS TEMP_ZONE_3",
      "[Ten.Dryer] AS TEMP_ZONE_4",
      "[Ten.No.1 Unwinder] AS TENSION_UNWIND_1",
      "[Ten.No.2 Unwinder] AS TENSION_UNWIND_2",
      "[Ten.Rewinder] AS TENSION_REWIND",
      "[Rewinder Taper No.] AS TENSION_TAPER_REWIND",
    ],
    unitOverrides: {
      TENSION_UNWIND_1: "N",
      TENSION_UNWIND_2: "N",
    },
  },
  {
    id: "SB01",
    name: "SB-01",
    brand: "",
    isMES: false,
    processType: "Laminate",
    axMachineId: "SB-01",
    tableName: null,
    columns: [],
  },
  {
    id: "SB04",
    name: "SB-04 Beiren",
    brand: "Beiren",
    isMES: true,
    processType: "Laminate",
    axMachineId: "SB-04",
    tableName: "[KEP_LOG].[dbo].[View_SB04_Beiren]",
    timestampColumn: "[SERVER TIMESTAMP]",
    columns: [],
  },
];

module.exports = {
  LAMINATE_MACHINES,
};
