const LAMINATE_MACHINES = [
  {
    ///  แยากเป็น 09 grave, free , flxo ///// { 3 var}
    id: "1LB09",
    name: "1LB-09 Bobst",
    brand: "Bobst",
    isMES: true,
    processType: "Laminate",
    axMachineId: "1LB-09",
    tableName: "[KEP_LOG].[dbo].[View_1LB09_Bobst]",
    timestampColumn: "[SERVER TIMESTAMP]",
    columns: [
      "[SERVER TIMESTAMP] AS SERVER_TIMESTAMP",
      "[Machine : Speed] AS LINE_SPEED",
      "[Tunnel : Zone 1 : Temperature] AS TEMP_ZONE_1",
      "[Tunnel : Zone 2 : Temperature] AS TEMP_ZONE_2",
      "'' AS TEMP_TANK_A",
      "'' AS TEMP_A_B",
      "'' AS TEMP_HOSE_AB",
      "[Coating 1- Metering and blade roller- Water- Temperature] AS TEMP_COATING_FM_BR_WR",
      "[Laminator : Hot Roll : Water Temperature] AS TEMP_LAMINATOR_HOT_ROLL",
      "[Unwinder 1 : Tension] AS TENSION_UNWIND_1",
      "[Unwinder 2 : Tension] AS TENSION_UNWIND_2",
      "[Rewinder : Tension] AS TENSION_REWIND",
      "[Rewinder : Tension Taper] AS TENSION_TAPER_REWIND",
      "[Coating : Rotogravure Trolley : CoatingRoll : Nip : Operator : Pressure] AS PRESSURE_COATING_GR_OP",
      "[Coating : Rotogravure Trolley : CoatingRoll : Nip : Motor : Pressure] AS PRESSURE_COATING_GR_MO",
      "[Coating : SI Transfer Roll : Operator : Pressure] AS PRESSURE_COATING_FR_OP",
      "[Coating : SI Transfer Roll : Motor : Pressure] AS PRESSURE_COATING_FR_MO",
      "[Coating : Inlet : Tension] AS TENSION_INLET_COATING",
      "[Coating : Outlet : Tension] AS TENSION_OUTLET_COATING",
      "[Unwinder 2 : Infeed ( D.g ) - Tension] AS TENSION_UNWIND2_INFEED",
      "[Laminator : Nip Roll : Operator : Pressure] AS PRESSURE_NIP_OPERATOR",
      "[Laminator : Nip Roll : Motor : Pressure] AS PRESSURE_NIP_MOTOR",
      "[Coating : Rotogravure Trolley : Smoothing Roll Speed] AS SMOOTHING_ROLL",
      "[Unwinder 1 : Treatment : Specific Power] AS CORONA_POWER_UW1",
      "[Unwinder 2 : Corona : Specific Power] AS CORONA_POWER_UW2",
    ],
    unitOverrides: {
      TENSION_UNWIND_1: "N",
      TENSION_UNWIND_2: "N",
      TENSION_REWIND: "N",
      PRESSURE_NIP_OPERATOR: "Bar",
      PRESSURE_NIP_MOTOR: "Bar",
      PRESSURE_COATING_GR_OP: "Bar",
      PRESSURE_COATING_GR_MO: "Bar",
      PRESSURE_COATING_FR_OP: "Bar",
      PRESSURE_COATING_FR_MO: "Bar",
    },
    supportedSolventTypes: [1, 2, 3],
    solventTypeRules: {
      1: {
        detailIndex: 1,
        name: "Solvent Base Gravure",
        inactiveKeys: [
          "SPLICE_SPEED",
          "TEMP_TANK_A",
          "TEMP_A_B",
          "TEMP_HOSE_AB",
          "PRESSURE_COATING_FR_OP",
          "PRESSURE_COATING_FR_MO",
        ],
      },
      2: {
        detailIndex: 2,
        name: "Solvent Free",
        inactiveKeys: ["SPLICE_SPEED", "TEMP_ZONE_1", "TEMP_ZONE_2"],
      },
      3: {
        detailIndex: 3,
        name: "Solvent Base Flexo",
        inactiveKeys: [
          "SPLICE_SPEED",
          "TEMP_TANK_A",
          "TEMP_A_B",
          "TEMP_HOSE_AB",
          "PRESSURE_COATING_FR_OP",
          "PRESSURE_COATING_FR_MO",
        ],
      },
    },
  },
  {
    id: "LB10",
    name: "LB-10 Bobst (Under Construction)",
    brand: "Bobst",
    isMES: true,
    processType: "Laminate",
    axMachineId: "LB-10",
    tableName: null,
    columns: [],
  },
  {
    id: "1LL07",
    name: "1LL-07 Comexi (Under Construction)",
    brand: "Comexi",
    isMES: true,
    processType: "Laminate",
    axMachineId: "1LL-07",
    tableName: "[KEP_LOG].[dbo].[View_1LL07_Comexi]",
    timestampColumn: "[SERVER TIMESTAMP]",
    columns: [
      "[SERVER TIMESTAMP] AS SERVER_TIMESTAMP",
      "[ACTUAL SPEED] AS LINE_SPEED",
      "'' as TEMP_TANK_A",
      "'' as TEMP_A_B",
      "'' as TEMP_HOSE_AB",
      "'' as TEMP_COATING_FM_BR_WR",
      "'' as TEMP_LAMINATOR_HOT_ROLL",
      "[UNW1 SP TENSION] as TENSION_UNWIND_1",
      "[UNWINDER2 SP TENSION] as TENSION_UNWIND_2",
      "[REWINDER SP TENSION] as TENSION_REWIND",
      "[REWINDER SP TAPER] as TENSION_TAPER_REWIND",
      "'' as TENSION_INLET_COATING",
      "'' as TENSION_OUTLET_COATING",
    ],
    unitOverrides: {
      TENSION_UNWIND_1: "Kg",
      TENSION_UNWIND_2: "Kg",
      TENSION_REWIND: "Kg",
      TENSION_TAPER_REWIND: "N",
      TENSION_INLET_COATING: "Kg",
      TENSION_OUTLET_COATING: "Kg",
    },
  },
  {
    id: "2LB06",
    name: "2LB-06 Fuji Kikai (Under Construction)",
    brand: "FujiKikai",
    isMES: true,
    processType: "Laminate",
    axMachineId: "2LB-06",
    tableName: "[KEP_LOG].[dbo].[View_2LB06_FujiKikai]",
    timestampColumn: "[SERVER TIMESTAMP]",
    columns: [
      "[SERVER TIMESTAMP] AS SERVER_TIMESTAMP",
      "[Speed.Actual Speed] AS LINE_SPEED",
      "[Speed.Rewinder Splice Speed Max Set] AS SPLICE_SPEED",
      "[Temp.No.1 Zone] AS TEMP_ZONE_1",
      "[Temp.No.2 Zone] AS TEMP_ZONE_2",
      "[Temp.No.3 Zone] AS TEMP_ZONE_3",
      "[Temp.Lami Heater] AS TEMP_LAMINATOR_HOT_ROLL",
      "[Ten.No.1 Unwinder] AS TENSION_UNWIND_1",
      "[Ten.No.2 Unwinder] AS TENSION_UNWIND_2",
      "[Ten.Rewinder] AS TENSION_REWIND",
      "'' AS PRESSURE_COATING_GR_OP",
      "'' AS PRESSURE_COATING_GR_MO",
      "'' AS TENSION_INLET_COATING",
      "'' AS TENSION_OUTLET_COATING",
      "'' AS PRESSURE_NIP_OPERATOR",
      "'' AS PRESSURE_NIP_MOTOR",
    ],
    unitOverrides: {
      TENSION_UNWIND_1: "N",
      TENSION_UNWIND_2: "N",
      TENSION_REWIND: "N",
    },
  },
  {
    id: "SB01",
    name: "SB-01",
    brand: "",
    isMES: false,
    processType: "Laminate",
    axMachineId: "SB-01",
    tableName: null,
    columns: [],
  },
  {
    id: "SB04",
    name: "SB-04 Beiren (Under Construction)",
    brand: "Beiren",
    isMES: true,
    processType: "Laminate",
    axMachineId: "SB-04",
    tableName: "[KEP_LOG].[dbo].[View_SB04_Beiren]",
    timestampColumn: "[SERVER TIMESTAMP]",
    columns: [
      "[SERVER TIMESTAMP] AS SERVER_TIMESTAMP",
      "[Speed (m/min)] AS LINE_SPEED",
      "'' AS TEMP_ZONE_1",
      "'' AS TEMP_ZONE_2",
      "'' AS TEMP_ZONE_3",
      "'' AS TEMP_ZONE_4",
      "'' AS TENSION_UNWIND_1",
      "'' AS TENSION_UNWIND_2",
      "[RW. Tension] AS TENSION_REWIND",
      "'' AS TENSION_TAPER_REWIND",
      "[Coat Tension] AS TENSION_INLET_COATING",
      "'' AS TENSION_OUTLET_COATING",
    ],
    unitOverrides: {
      TENSION_REWIND: "N",
      TENSION_TAPER_REWIND: "N",
      TENSION_INLET_COATING: "N",
      TENSION_OUTLET_COATING: "N",
    },
  },
];

const SOLVENT_PROCESS_NAMES = {
  1: "Solvent Base Gravure",
  2: "Solvent Free",
  3: "Solvent Base Flexo",
};

module.exports = {
  LAMINATE_MACHINES,
  SOLVENT_PROCESS_NAMES,
};
