const STANDARD_PARAMETERS = [
  { key: "LINE_SPEED", param_id: 1, name: "Line Speed", category: "Speed", set_point: "", unit: "m/min", type: "numeric" },
  { key: "SPICE_SPEED", param_id: 2, name: "Spice Speed", category: "Speed", set_point: "", unit: "m/min", type: "numeric" },
  { key: "TEMP_ZONE_1", param_id: 3, name: "Temp No. 1", category: "Temperature", set_point: "", unit: "°C", type: "numeric" },
  { key: "TEMP_ZONE_2", param_id: 4, name: "Temp No. 2", category: "Temperature", set_point: "", unit: "°C", type: "numeric" },
  { key: "TEMP_ZONE_3", param_id: 5, name: "Temp No. 3", category: "Temperature", set_point: "", unit: "°C", type: "numeric" },
  { key: "TEMP_ZONE_4", param_id: 6, name: "Temp No. 4", category: "Temperature", set_point: "", unit: "°C", type: "numeric" },
  { key: "TEMP_TANK_A", param_id: 7, name: "Temp Tank A", category: "Temperature", set_point: "", unit: "°C", type: "numeric" },
  { key: "TEMP_A_B", param_id: 8, name: "Temp A, B", category: "Temperature", set_point: "", unit: "°C", type: "numeric" },
  { key: "TEMP_HOSE_AB", param_id: 9, name: "Adhesive Hose A, B", category: "Temperature", set_point: "", unit: "°C", type: "numeric" },
  { key: "TEMP_COATING_FM_BR_WR", param_id: 10, name: "Coating : Free : Metening and Blade Roller Water Temp", category: "Temperature", set_point: "", unit: "°C", type: "numeric" },
  { key: "TEMP_LAMINATOR_HOT_ROLL", param_id: 11, name: "Laminator : Hot roll Temp", category: "Temperature", set_point: "", unit: "°C", type: "numeric" },
  { key: "TENSION_UNWIND_1", param_id: 12, name: "1ˢᵗ Unwind Tension", category: "Tension", set_point: "", unit: "Kg./N", type: "numeric" },
  { key: "TENSION_UNWIND_2", param_id: 13, name: "2ⁿᵈ Unwind Tension", category: "Tension", set_point: "", unit: "Kg./N", type: "numeric" },
  { key: "TENSION_REWIND", param_id: 14, name: "Rewind Tension", category: "Tension", set_point: "", unit: "Kg./N", type: "numeric" },
  { key: "TENSION_TAPER_REWIND", param_id: 15, name: "Rewinder : Tension Taper", category: "Tension", set_point: "", unit: "%", type: "numeric" },
  { key: "PRESSURE_COATING_GR_OP", param_id: 16, name: "Coating : Gravure : Coating Pressure : Operation", category: "Pressure", set_point: "", unit: "Bar/Mpa", type: "numeric" },
  { key: "PRESSURE_COATING_GR_MO", param_id: 17, name: "Coating : Gravure : Coating Pressure : Motor", category: "Pressure", set_point: "", unit: "Bar/Mpa", type: "numeric" },
  { key: "PRESSURE_COATING_FR_OP", param_id: 18, name: "Coating : Free : Coating Pressure : Operation", category: "Pressure", set_point: "", unit: "Bar/Mpa", type: "numeric" },
  { key: "PRESSURE_COATING_FR_MO", param_id: 19, name: "Coating : Free : Coating Pressure : Motor", category: "Pressure", set_point: "", unit: "Bar/Mpa", type: "numeric" },
  { key: "TENSION_INLET_COATING", param_id: 20, name: "Coating : Inlet : Tension", category: "Tension", set_point: "", unit: "N", type: "numeric" },
  { key: "TENSION_OUTLET_COATING", param_id: 21, name: "Coating : Outlet : Tension", category: "Tension", set_point: "", unit: "N", type: "numeric" },
  { key: "TENSION_UNWIND2_INFEED", param_id: 22, name: "Unwind 2 : Infeed : Tension", category: "Tension", set_point: "", unit: "N", type: "numeric" },
  { key: "PRESSURE_NIP_OPERATOR", param_id: 23, name: "Laminator : Nip roll : Operator Pressure", category: "Pressure", set_point: "", unit: "Bar/Mpa", type: "numeric" },
  { key: "PRESSURE_NIP_MOTOR", param_id: 24, name: "Laminator : Nip roll : Motor Pressure", category: "Pressure", set_point: "", unit: "Bar/Mpa", type: "numeric" },
  { key: "SMOOTHING_ROLL", param_id: 25, name: "Smooting Roll : % Speed", category: "Status", set_point: "", unit: "ปกติ/ไม่ปกติ", type: "status" },
  { key: "CORONA_INSIDE", param_id: 26, name: "Corona Treated Inside (ด้านใน)", category: "Status", set_point: "", unit: "มี/ไม่มี", type: "status" },
  { key: "CORONA_OUTSIDE", param_id: 27, name: "Corona Treated Outside (ด้านนอก)", category: "Status", set_point: "", unit: "มี/ไม่มี", type: "status" },
  { key: "CORONA_POWER_UW1", param_id: 28, name: "Corona Specific Power (UW1)", category: "Corona", set_point: "", unit: "Watt", type: "numeric" },
  { key: "CORONA_POWER_UW2", param_id: 29, name: "Corona Specific Power (UW2)", category: "Corona", set_point: "", unit: "Watt", type: "numeric" },
];

module.exports = {
  STANDARD_PARAMETERS,
};
