const BLOWNFILM_MACHINES = [
  {
    id: "1BF01",
    name: "1BF-01 Blownfilm",
    brand: "Blownfilm",
    isMES: true,
    processType: "BlownFilm",
    axMachineId: "1BF-01",
    tableName: "[KEP_LOG].[dbo].[View_1BF01_Blownfilm]",
    timestampColumn: "[SERVER TIMESTAMP]",
    columns: [
      "[SERVER TIMESTAMP]",
      "[Take Off Link Speed] AS [LINE_SPEED]",
      "[Take Off] AS [Take_Off]",
      "[Nip] AS [Nip]",
      "[DOS_HOFFSpeedSpt] AS [DOS_HOFFSpeedSpt]",
      "[DOS_HOFFSpeedSpt_int_1] AS [DOS_HOFFSpeedSpt_int_1]",
      "[Exhaust] AS [Exhaust]",
      "[Supply] AS [Supply]",
      "[Air Ring] AS [Air_Ring]",
      "[Air ring height] AS [Air_ring_height]",
      "[Air Cooling Unit Supply Air] AS [Air_Cooling_Unit_Supply_Air]",
      "[Layflat] AS [Layflat]",
      "[DOS_LFWSpt] AS [DOS_LFWSpt]",
      "[DOS_LFWSpt_int_1] AS [DOS_LFWSpt_int_1]",
      "[Cage Height] AS [Cage_Height]",
      "[Cage Bubble] AS [Cage_Bubble]",
      "[Gauge] AS [Gauge]",
      "[All Extruder set Thiknes] AS [All_Extruder_set_Thiknes]",
      "[Thruput] AS [Thruput]",
      "[All Extruder Thruput] AS [All_Extruder_Thruput]",
      "[DOS_ThroughputSpt_int_1] AS [DOS_ThroughputSpt_int_1]",
      "[Feed plate Act] AS [Feed_plate_Act]",
      "[Feed plate Set] AS [Feed_plate_Set]",
      "[Housing bottom Act] AS [Housing_bottom_Act]",
      "[Housing bottom Set] AS [Housing_bottom_Set]",
      "[Housing Center Act] AS [Housing_Center_Act]",
      "[Housing Center Set] AS [Housing_Center_Set]",
      "[Die adapter Act] AS [Die_adapter_Act]",
      "[Die adapter Set] AS [Die_adapter_Set]",
      "[Die gap Act] AS [Die_gap_Act]",
      "[Die gap Set] AS [Die_gap_Set]",
      "[DIE1_Temp_Alm_Spt_time] AS [DIE1_Temp_Alm_Spt_time]",
      "[Temperatures A] AS [Temperatures_A]",
      "[Temperatures] AS [Temperatures]",
      "[Pre-take-off tension] AS [Pre_take_off_tension]",
      "[Rotation Angle Act] AS [Rotation_Angle_Act]",
      "[Rotation Angle Set Left] AS [Rotation_Angle_Set_Left]",
      "[Rotation Angle Set Right] AS [Rotation_Angle_Set_Right]",
      "[Rotator] AS [Rotator]",
      "[Recipe] AS [Recipe]",
      "[Order Number] AS [Order_Number]",
    ],
  },
];

module.exports = {
  BLOWNFILM_MACHINES,
};
