// Standard parameters for BlownFilm process (40 parameters)
const BLOWNFILM_PARAMETERS = [
  { key: "LINE_SPEED", param_id: 1, name: "Take Off Link Speed", category: "Speed", set_point: "", unit: "m/min", type: "numeric" },
  { key: "Take_Off", param_id: 2, name: "Take Off Speed", category: "Speed", set_point: "", unit: "m/min", type: "numeric" },
  { key: "Nip", param_id: 3, name: "Nip Speed", category: "Speed", set_point: "", unit: "m/min", type: "numeric" },
  { key: "DOS_HOFFSpeedSpt", param_id: 4, name: "DOS HOFFSpeed Spt", category: "Speed", set_point: "", unit: "m/min", type: "numeric" },
  { key: "DOS_HOFFSpeedSpt_int_1", param_id: 5, name: "DOS HOFFSpeed Spt (Int)", category: "Speed", set_point: "", unit: "m/min", type: "numeric" },
  { key: "Exhaust", param_id: 6, name: "Exhaust", category: "Speed", set_point: "", unit: "%", type: "numeric" },
  { key: "Supply", param_id: 7, name: "Supply Air", category: "Speed", set_point: "", unit: "%", type: "numeric" },
  { key: "Air_Ring", param_id: 8, name: "Air Ring Blower", category: "Speed", set_point: "", unit: "%", type: "numeric" },
  { key: "Air_ring_height", param_id: 9, name: "Air Ring Height", category: "Dimension & Gauge", set_point: "", unit: "mm", type: "numeric" },
  { key: "Layflat", param_id: 10, name: "Layflat Width (Act)", category: "Dimension & Gauge", set_point: "", unit: "mm", type: "numeric" },
  { key: "DOS_LFWSpt", param_id: 11, name: "Layflat Width (Spt)", category: "Dimension & Gauge", set_point: "", unit: "mm", type: "numeric" },
  { key: "DOS_LFWSpt_int_1", param_id: 12, name: "Layflat Width (Int Spt)", category: "Dimension & Gauge", set_point: "", unit: "mm", type: "numeric" },
  { key: "Cage_Height", param_id: 13, name: "Cage Height", category: "Dimension & Gauge", set_point: "", unit: "mm", type: "numeric" },
  { key: "Cage_Bubble", param_id: 14, name: "Cage Bubble", category: "Dimension & Gauge", set_point: "", unit: "mm", type: "numeric" },
  { key: "Gauge", param_id: 15, name: "Gauge (Thickness)", category: "Dimension & Gauge", set_point: "", unit: "µm", type: "numeric" },
  { key: "All_Extruder_set_Thiknes", param_id: 16, name: "Set Thickness", category: "Dimension & Gauge", set_point: "", unit: "µm", type: "numeric" },
  { key: "Thruput", param_id: 17, name: "Total Throughput (Act)", category: "Throughput", set_point: "", unit: "", type: "numeric" },
  { key: "All_Extruder_Thruput", param_id: 18, name: "All Extruder Thruput (Spt)", category: "Throughput", set_point: "", unit: "", type: "numeric" },
  { key: "DOS_ThroughputSpt_int_1", param_id: 19, name: "DOS Throughput Spt (Int)", category: "Throughput", set_point: "", unit: "", type: "numeric" },
  { key: "Air_Cooling_Unit_Supply_Air", param_id: 20, name: "ACU Supply Air Temp", category: "Temperature", set_point: "", unit: "°C", type: "numeric" },
  { key: "Feed_plate_Act", param_id: 21, name: "Feed Plate (Act)", category: "Temperature", set_point: "", unit: "°C", type: "numeric" },
  { key: "Feed_plate_Set", param_id: 22, name: "Feed Plate (Set)", category: "Temperature", set_point: "", unit: "°C", type: "numeric" },
  { key: "Housing_bottom_Act", param_id: 23, name: "Housing Bottom (Act)", category: "Temperature", set_point: "", unit: "°C", type: "numeric" },
  { key: "Housing_bottom_Set", param_id: 24, name: "Housing Bottom (Set)", category: "Temperature", set_point: "", unit: "°C", type: "numeric" },
  { key: "Housing_Center_Act", param_id: 25, name: "Housing Center (Act)", category: "Temperature", set_point: "", unit: "°C", type: "numeric" },
  { key: "Housing_Center_Set", param_id: 26, name: "Housing Center (Set)", category: "Temperature", set_point: "", unit: "°C", type: "numeric" },
  { key: "Die_adapter_Act", param_id: 27, name: "Die Adapter (Act)", category: "Temperature", set_point: "", unit: "°C", type: "numeric" },
  { key: "Die_adapter_Set", param_id: 28, name: "Die Adapter (Set)", category: "Temperature", set_point: "", unit: "°C", type: "numeric" },
  { key: "Die_gap_Act", param_id: 29, name: "Die Gap (Act)", category: "Temperature", set_point: "", unit: "°C", type: "numeric" },
  { key: "Die_gap_Set", param_id: 30, name: "Die Gap (Set)", category: "Temperature", set_point: "", unit: "°C", type: "numeric" },
  { key: "DIE1_Temp_Alm_Spt_time", param_id: 31, name: "Die Temp Alm Spt Time", category: "Temperature", set_point: "", unit: "s", type: "numeric" },
  { key: "Temperatures_A", param_id: 32, name: "Roller Temp A", category: "Temperature", set_point: "", unit: "°C", type: "numeric" },
  { key: "Temperatures", param_id: 33, name: "Pre-nip Temperature", category: "Temperature", set_point: "", unit: "°C", type: "numeric" },
  { key: "Pre_take_off_tension", param_id: 34, name: "Pre-take-off Tension", category: "Tension & Rotation", set_point: "", unit: "", type: "numeric" },
  { key: "Rotation_Angle_Act", param_id: 35, name: "Rotation Angle (Act)", category: "Tension & Rotation", set_point: "", unit: "", type: "numeric" },
  { key: "Rotation_Angle_Set_Left", param_id: 36, name: "Rotation Angle Set Left", category: "Tension & Rotation", set_point: "", unit: "", type: "numeric" },
  { key: "Rotation_Angle_Set_Right", param_id: 37, name: "Rotation Angle Set Right", category: "Tension & Rotation", set_point: "", unit: "", type: "numeric" },
  { key: "Rotator", param_id: 38, name: "Rotator", category: "Tension & Rotation", set_point: "", unit: "%", type: "numeric" },
  { key: "Recipe", param_id: 39, name: "Recipe", category: "Information", set_point: "", unit: "", type: "numeric" },
  { key: "Order_Number", param_id: 40, name: "Order Number", category: "Information", set_point: "", unit: "", type: "numeric" },
];

module.exports = {
  BLOWNFILM_PARAMETERS,
};
